version: '2'
services:
  app:
    container_name: backend-api

    build:
      context: .
      dockerfile: docker/vue-storefront-api/Dockerfile

    depends_on:
      - es1
      - redis

    env_file: docker/vue-storefront-api/default.env

    environment:
      VS_ENV: dev

    volumes:
      - './config:/var/www/config'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './migrations:/var/www/migrations'
      - './package.json:/var/www/package.json'
      - './scripts:/var/www/scripts'
      - './src:/var/www/src'
      - './var:/var/www/var'

    tmpfs:
      - /var/www/dist

    ports:
      - '8080:8080'

    networks:
      - vuestorefrontapi_default

networks:
  vuestorefrontapi_default:
    external: true