version: '2'
services:
  es1:
    container_name: elasticsearch
    build: docker/elasticsearch/
    volumes:
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - 'esdat1:/usr/share/elasticsearch/data'

    networks:
      default:
        aliases:
          - elasticsearch

      vuestorefrontcoreshopapp_coreshop:

    ports:
      - '9200:9200'
      - '9300:9300'

    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"

  kibana:
    build: docker/kibana/
    volumes:
      - ./docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - '5601:5601'
    depends_on:
      - es1

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

volumes:
  esdat1:

networks:
  vuestorefrontcoreshopapp_coreshop:
    external: true